name: api_client
description: A simple API client in Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.12.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  api_client:
    script: client.dart